name = "bomad"
version = "1.0.0"
description = "A robust, embeddable Gleam implementation of the Nomad-LISP dialect"
licences = ["MIT"]
repository = { type = "github", user = "Moritisimor", repo = "bomad" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
