#!/usr/bin/env nomad
(let space " ")

(letfun char_to_morse (char)
	(switch (lower char)
		(space " / ")
		("a" ".-")
		("b" "-...")
		("c" "-.-.")
		("d" "-..")
		("e" ".")
		("f" "..-.")
		("g" "--.")
		("h" "....")
		("i" "..")
		("j" ".---")
		("k" "-.-")
		("l" ".-..")
		("m" "--")
		("n" "-.")
		("o" "---")
		("p" ".--.")
		("q" "--.-")
		("r" ".-.")
		("s" "...")
		("t" "-")
		("u" "..-")
		("v" "...-")
		("w" ".--")
		("x" "-..-")
		("y" "-.--")
		("z" "--..")
		("1" ".----")
		("2" "..---")
		("3" "...--")
		("4" "....-")
		("5" ".....")
		("6" "-....")
		("7" "--...")
		("8" "---..")
		("9" "----.")
		("0" "-----")
		("." ".-.-.-")
		("?" "..--..")
		(";" "-.-.-")
		(":" "---...")
		("/" "-..-.")
		("+" ".-.-.")
		("-" "-....-")
		("=" "-...-")
		(_ (throw (sprint "Cannot convert '" char "' to morse code")))))

(letfun text_to_morse (text) 
	(foldl (lambda (acc char)
		(sprint acc (char_to_morse char) " "))
	"" (chars text)))

(if (= args 1)
	(do
		(println "Usage: morse.nomad <words...>")
		(exit 1))
		
	(try 
		(do
			(let converted 
				(mapi (lambda (m i)
					(if (= i 0)
						(text_to_morse m)
						(sprint "/ " (text_to_morse m))))
			(cdr args)))
			
			(println (foldl + "" converted)))
			
		(do
			(println "Sorry, but one or more of the characters that you entered could not be converted to morse code.")
			(exit 1))))
